# Não mexa! Isso serve para funções internas do plugin
config-version: 1.1.0

# EVENTO

# Valor máximo de dinheiro para o vencedor
max-premio-evento: 10000
# Se o plugin irá anunciar o evento automaticamente
auto-anunciar: true
# Tempo de intervalo entre os anúncios (em segundos)
anunciar-evento: 120

# QUIZ

# Valor máximo de dinheiro para o vencedor
max-premio-quiz: 1000
# Tempo de intervalo entre os anúncios (em segundos)
anunciar-quiz: 60

# VOUF

# Valor máximo de dinheiro para o vencedor
max-premio-vouf: 500
# Tempo de intervalo entre os anúncios (em segundos)
anunciar-vouf: 60

# BOLÃO

# Se o bolão vai ser ativo automaticamente no servidor
bolao-ativo: true
# De quanto em quanto tempo ocorrerá um bolão (em minutos)
bolao-intervalo: 30
# Tempo de intervalo entre anúncios de um bolão já criado (em segundos)
anunciar-bolao: 60
# Quantidade de vezes que o bolão será anunciado antes de finalizar
bolao-anuncios: 5
# Se staff pode ou não apostar no bolão
staff-apostar: true
# Valor máximo de dinheiro inicial em um bolão manual
max-premio-bolao: 10000
# Valores possíveis de serem o valor inicial de um bolão automático
bolao-valores:
  - 500
  - 1000
  - 2000

# LOTERIA

# Se a loteria vai ser ativa automaticamente no servidor
loteria-ativo: true
# De quanto em quanto tempo ocorrerá uma loteria (em minutos)
loteria-intervalo: 60
# Tempo de intervalo entre anúncios de uma loteria já criada (em segundos)
loteria-anunciar: 60
# O número máximo que a loteria pode sortear
loteria-max-numero: 60
# O número máximo de vezes de anúncios da loteria automática (em segundos)
loteria-anuncios: 5
# O número máximo de vezes que um jogador pode apostar (-1 para infinito)
loteria-max-apostas: 5
# Valor máximo de prêmio em uma loteria manual
max-premio-loteria: 5000
# Valores possíveis de serem o prêmio da loteria automática
loteria-premios:
  - 500
  - 1000
  - 2000
  - 3000

# ENQUETE

anunciar-enquete: 60
